### ISSUE TITLE
PHP8 support

### ISSUE THREAD

**Issue by malanx** [thephpleague/color-extractor#64]
Hi, I'm getting an "Image must be a gd resource"

PHP has moved to make GD an object instead of a resource, because GD is now an object, it will never be a resource and this causes an error

**Comment by CodeJunkieio** [comment]
Removing this statement from Palette.php@fromGD works for me however I haven't run all of the tests
`if (!is_resource($image) || get_resource_type($image) != 'gd')`

**Comment by dorianfm** [comment]
PHP 8.0 changes GD to return a `GdImage` object from `imagecreatefromstring`

I'd recommend changing the line @malanx references above to

`if (!($image instanceof \GdImage) && (!is_resource($image) || get_resource_type($image) != 'gd'))`

so that the error is still thrown if something invalid is passed as $image, whilst creating PHP 8 compatabilty (for this error...) and keeping backward compatibility 

I've made a fork with this change, but not written tests for it, happy to issue a PR if that's OK to merge.

**Comment by martinbean** [comment]
The requirements in **composer.json** need to be amended given that this library is _not_ compatible with PHP ^8.0 in its current state.
