### ISSUE TITLE
Error on Ubuntu 22.04 and OpenSSL 3.0.2

### ISSUE THREAD

**Issue by vinprom1** [thephpleague/color-extractor#75]
file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages: error:0A000126:SSL routines::unexpected eof while reading

SSL routines::unexpected eof while reading at Palette.php:55

**Comment by colinodell** [comment]
Unfortunately this won't be something caused by this library.  If I had to take a guess:

1. Maybe OpenSSL has a bug, or PHP doesn't like that version
2. The server you're connecting to isn't properly configured

You're welcome to try the new curl-based `fromUrl()` method in the upcoming 0.4.0 release, but I can't guarantee it'll work there because this issue is happening outside of this library.
